// Dishes
export const GET_DISHES = 'GET_DISHES';
export const ADD_DISH = 'ADD_DISH';
export const REMOVE_DISH = 'REMOVE_DISH';
export const RESET_DISHES = 'RESET_DISHES';

// Ingredient
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';

// Ingredient stored in Freezer
export const GET_INGREDIENTS_IN_FREEZER = 'GET_INGREDIENTS_IN_FREEZER';
export const ADD_INGREDIENT_TO_FREEZER = 'ADD_INGREDIENT_TO_FREEZER';
export const REMOVE_INGREDIENT_FROM_FREEZER = 'REMOVE_INGREDIENT_FROM_FREEZER';
export const DELETE_FREEZER_CONTENT = 'DELETE_FREEZER_CONTENT';

// Categories
export const ADD_DISH_CATEGORY = 'ADD_DISH_CATEGORY';
export const REMOVE_DISH_CATEGORY = 'REMOVE_DISH_CATEGORY';
export const ADD_INGREDIENT_CATEGORY = 'ADD_INGREDIENT_CATEGORY';
export const REMOVE_INGREDIENT_CATEGORY = 'REMOVE_INGREDIENT_CATEGORY';

// Planned Dishes
export const ADD_PLANNED_DISH = 'ADD_PLANNED_DISH';
export const RESET_PLANNED_DISHES = 'RESET_PLANNED_DISHES';

// Shopping Cart
export const GET_CART = 'GET_CART';
export const GET_DISHES_COUNT = 'GET_DISHES_COUNT';
export const ADD_DISH_TO_CART = 'ADD_DISH_TO_CART';
export const REMOVE_DISH_FROM_CART = 'REMOVE_DISH_FROM_CART';
export const DELETE_CART = 'DELETE_CART';